typography_spectrum: 0.5397299414034933
color:
  brandStrength: 0.6746061118319631
  lightness: 0.9810982281342149
  saturation: 0.3169009641278535
  rhythmicContrast: 0.878322172909975
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
layout_spectrum: 0.8748485986143351
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8ce98a55-87fe-4ec8-a89e-5d9b02ad7c91.png
name: Nathaliet
navigation:
  - name: Home
    url: 'http://thegrid.ai/nathaliet/'
    type: external
  - name: Bodys
    url: 'https://thegrid.ai/nathaliet-body/'
    type: external
  - name: Crop Tops
    url: 'https://thegrid.ai/nathaliet-croptops'
    type: external
  - name: Blazers
    url: 'https://thegrid.ai/nathaliet-blazers'
    type: external
  - name: Vestidos
    url: 'https://thegrid.ai/nathaliet-vestidos'
    type: external
  - name: Trajes de Baño
    url: 'https://thegrid.ai/nathaliet-trajes-de-bano/'
    type: external
  - name: '#NathalietMe'
    url: 'https://thegrid.ai/nathalietme/'
    type: external
  - name: Agendar una cita
    url: 'http://m.me/nathalietme'
    type: external
  - name: Acerca de Nathaliet
    url: 'https://thegrid.ai/nathaliet/acerca-de-nathaliet/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/998d24db-e6bb-4d83-a7e4-adb130ecf0c5.png
