layout_spectrum: 0.899153339676559
typography_spectrum: 0.5997598976828158
color:
  brandStrength: 0.6804493544623256
  lightness: 0.41131243319250643
  saturation: 0.9380890924949199
  rhythmicContrast: 0.6925652797799557
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
name: nathaliet blazers
navigation:
  - name: Home
    url: 'http://thegrid.ai/nathaliet/'
    type: external
  - name: Poleras
    url: 'https://thegrid.ai/nathaliet-poleras/'
    type: external
  - name: Crop Tops
    url: 'https://thegrid.ai/nathaliet-croptops'
    type: external
  - name: Blazers
    url: 'https://thegrid.ai/nathaliet-blazers'
    type: external
  - name: Vestidos
    url: 'https://thegrid.ai/nathaliet-vestidos'
    type: external
  - name: Trajes de Baño
    url: 'https://thegrid.ai/nathaliet-trajes-de-bano/'
    type: external
  - name: '#NathalietMe'
    url: 'https://thegrid.ai/nathalietme/'
    type: external
  - name: Agendar una cita
    url: 'http://m.me/nathalietme'
    type: external
